### DISCUSSION TITLE
Use OLED 126x64 Layout on Corne Without Dongle, Only With CUSTOM SCREEN

### DISCUSSION THREAD

**Discussion by radsonpatrick** [mctechnology17/zmk-config#3] [Q&A]
> Hello! I’d like to know if it would be possible to use the screen layout on a standard 126x64 OLED for the Corne without needing a dongle, relying solely on the CUSTOM SCREEN functionality. The default ZMK layout isn’t as practical, and the CUSTOM SCREEN offers a much better and more functional display.
>
> Note: I only have the central side with a display, so being able to monitor both batteries directly on the screen would be amazing!
>
> Any guidance or ideas on how this could be implemented?

**Comment by mctechnology17** [comment]
Hi, if possible, in your `build.yml` configuration file I added this:
`corne_left dongle_display oled_adapter_pro_micro_128x64`

And in your `west.yml` file write this:

 ```yml
manifest:
  remotes:
    …
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    …
    - name: zmk-oled-adapter
      remote: mctechnology17
      revision: main
    …
```

You can check the module for reference here (this can be done WITH and WITHOUT dongle):
https://github.com/mctechnology17/zmk-oled-adapter

**Reply by radsonpatrick** [reply]
i try build with config but not sucess !  i use my repo not create new!
`west.yml`:
```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/urob
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
      
    - name: zmk-oled-adapter
      remote: mctechnology17
      revision: main
  self:
    path: config
```
`build.yml`: 
```
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right dongle_display oled_adapter_pro_micro_128x32
  - board: nice_nano_v2
    shield: settings_reset

```
