### DISCUSSION TITLE
Help with build.yaml for nice!nano v2 + nice!view for each and Xiao ESP32C3 as dongle?

### DISCUSSION THREAD

**Discussion by DarrenVictoriano** [mctechnology17/zmk-config#6] [Q&A] [answered]
Hello,

I am using your repo as a module for my [zmk-config](https://github.com/DarrenVictoriano/zmk-config/tree/xiao_dongle), but I'm kind of confused for creating the correct `build.yaml`. 
Devices that I use:
left_corne: nice!nano v2 + nice!view
right_corne: nice!nano v2 + nice!view
dongle: Xiao ESP32C3 (no screen, just plain dongle)

In your example build, I'm not sure if I'm suppose to add `# peripheral_left + nice_nano_v2 + nice_view_gem`?

this is what I have so far:
```yaml
include:
  # nice_nano_v2 + nice_view
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_gem
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_View\"
    artifact-name: nice_corne_left_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_gem
    cmake-args: -DCONFIG_NICE_VIEW_GEM_ANIMATION=y
    artifact-name: nice_corne_right_view

  # xiao_dongle
  - board: seeeduino_xiao_ble
    shield: corne_dongle_xiao
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Xiao_Dongle\" -DCONFIG_ZMK_STUDIO=y
    artifact-name: xiao_corne_dongle_xiao
    snippet: studio-rpc-usb-uart
```

**Comment by mctechnology17** [comment, marked as answer]
> [!WARNING]
> Please do not confuse the `xiao` with the `esp32c3` because they are different hardware.

Hello, first place the `xiao` is not based on` esp32c3` but on the `NRF52840`, so I ask you to read the hardware admitted in the [official documentation of ZMK](https://zmk.dev/docs/hardware).

To obtain a versatile configuration and compilation, I recommend you to have the following in your compilation steps:

# build.yaml
```yaml
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view_gem
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_View\"
    artifact-name: nice_corne_left_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view_gem
    cmake-args: -DCONFIG_NICE_VIEW_GEM_ANIMATION=y
    artifact-name: nice_corne_right_view
  - board: nice_nano_v2
    shield: corne_left_peripheral nice_view_adapter nice_view_gem
    cmake-args: -DCONFIG_NICE_VIEW_GEM_ANIMATION=y
    artifact-name: nice_corne_left_peripheral_view

  # xiao_dongle
  - board: seeeduino_xiao_ble
    shield: corne_dongle_xiao
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Xiao_Dongle\" -DCONFIG_ZMK_STUDIO=y
    artifact-name: xiao_corne_dongle_xiao
    snippet: studio-rpc-usb-uart
```

With this `compilation / configuration` you can use your keyboard as follows:

# corne diagram without dongle

``` mermaid
classDiagram
class master_central {
        board: nice_nano_v2
        shield: corne_left nice_view_adapter nice_view_gem
	description: Communication with the slave and computer
	other: ...
        artifact-name(): nice_corne_left_view
    }

    class slave_right {
        board: nice_nano_v2
        shield: corne_right nice_view_adapter nice_view_gem
	description: Communication only with the master
	other: ...
        artifact-name(): nice_corne_right_view
    }

    master_central <|-- slave_right
```

# corne diagram with dongle
``` mermaid
classDiagram
class master_central {
        board: seeeduino_xiao_ble
        shield: corne_dongle_xiao
	description: Communication with slaves and computer
	other: ...
        artifact-name(): xiao_corne_dongle_xiao
    }

    class slave_left {
        board: nice_nano_v2
        shield: corne_left_peripheral nice_view_adapter nice_view_gem
	description: Communication only with the master
	other: ...
        artifact-name(): nice_corne_left_peripheral_view
    }

    class slave_right {
        board: nice_nano_v2
        shield: corne_right nice_view_adapter nice_view_gem
	description: Communication only with the master
	other: ...
        artifact-name(): nice_corne_right_view
    }

    master_central <|-- slave_left
    master_central <|-- slave_right
```
